export const pageConstants = {
  GETALL_REQUEST: 'PAGES_GETALL_REQUEST',
  GETALL_SUCCESS: 'PAGES_GETALL_SUCCESS',
  GETALL_FAILURE: 'PAGES_GETALL_FAILURE',

  EDIT_REQUEST: 'PAGE_EDIT_REQUEST',
  EDIT_SUCCESS: 'PAGE_EDIT_SUCCESS',
  EDIT_FAILURE: 'PAGE_EDIT_FAILURE',

  ADD_REQUEST: 'PAGE_ADD_REQUEST',
  ADD_SUCCESS: 'PAGE_ADD_SUCCESS',
  ADD_FAILURE: 'PAGE_ADD_FAILURE',

  DELETE_REQUEST: 'PAGE_DELETE_REQUEST',
  DELETE_SUCCESS: 'PAGE_DELETE_SUCCESS',
  DELETE_FAILURE: 'PAGE_DELETE_FAILURE',
};
