export const pageConstants = {
  REGISTER_REQUEST: 'PAGES_ADD_REQUEST',
  REGISTER_SUCCESS: 'PAGES_ADD_SUCCESS',
  REGISTER_FAILURE: 'PAGES_ADD_FAILURE',

  GETALL_REQUEST: 'PAGES_GET_ALL_REQUEST',
  GETALL_SUCCESS: 'PAGES_GET_ALL_SUCCESS',
  GETALL_FAILURE: 'PAGES_GET_ALL_FAILURE',
};
