import { createGlobalStyle } from "styled-components";

export const GlobalStyle = createGlobalStyle`
    /*-------------------------------------------------
    Style file contain theme components style
    -------------------------------------------------*/
    @import url(https://fonts.googleapis.com/css?family=Muli:300,300i,400,400i,500,600);
    
    
    /*
      Autogenerated theme file
    */
    /*----------------------------------------
      General Layout Style
    ------------------------------------------*/
    html,
    body
    {
        height: 100%;
    }
    
    body
    {
        background-color: ${props => props.theme.bodyBgColor};
    }
          
    
    select
    {
        width: 100%;
        height: 3rem;
        padding: 5px;
    
        border: none;
        border-bottom: 1px solid #bdbdbd;
        border-radius: 2px;
        background-color: transparent;
    }
    
    .container
    {
        width: 100%;
        max-width: 100% !important;
        margin: 0 auto;
        padding: 0 .5rem;
    }
    .container .dropdown-settings i.right
    {
        margin-left: 0;
    }
    
    @media only screen and (min-width: 601px)
    {
        .container
        {
            width: 100%;
        }
    }
    
    @media only screen and (min-width: 993px)
    {
        .container
        {
            width: 100%;
        }
        .sidenav-overlay
        {
            background-color: transparent;
        }
    }
    
    @media only screen and (min-width: 993px)
    {
        #main
        {
            padding-left: 250px;
        }
        #main.main-full
        {
            padding-left: 64px;
        }
        footer
        {
            padding-left: 250px;
        }
    }
    
    @media only screen and (max-width: 600px)
    {
        #main .content-wrapper-before
        {
            top: 56px;
        }
    }
    
    
    
    .height-100vh
    {
        height: 100vh;
    }
    
    button,
    html [type='button'],
    [type='reset'],
    [type='submit']
    {
        cursor: pointer;
    
        -webkit-appearance: none;
    }
    
    /*----------------------------------------
      Helper Classes
    ------------------------------------------*/
    
    
    .m-0
    {
        margin: 0 !important;
    }
    
    /* Margin Top */
    .mt-0
    {
        margin-top: 0 !important;
    }
    
    .mt-1
    {
        margin-top: 1% !important;
    }
    
    .mt-2
    {
        margin-top: 2% !important;
    }
    
    .mt-3
    {
        margin-top: 3% !important;
    }
    
    .mt-4
    {
        margin-top: 4% !important;
    }
    
    .mt-5
    {
        margin-top: 5% !important;
    }
    
    .mt-6
    {
        margin-top: 6% !important;
    }
    
    .mt-7
    {
        margin-top: 7% !important;
    }
    
    .mt-8
    {
        margin-top: 8% !important;
    }
    
    .mt-9
    {
        margin-top: 9% !important;
    }
    
    .mt-10
    {
        margin-top: 10% !important;
    }
    
    /* Margin Right */
    .mr-0
    {
        margin-right: 0 !important;
    }
    
    .mr-1
    {
        margin-right: 1% !important;
    }
    
    .mr-2
    {
        margin-right: 2% !important;
    }
    
    .mr-3
    {
        margin-right: 3% !important;
    }
    
    .mr-4
    {
        margin-right: 4% !important;
    }
    
    .mr-5
    {
        margin-right: 5% !important;
    }
    
    .mr-6
    {
        margin-right: 6% !important;
    }
    
    .mr-7
    {
        margin-right: 7% !important;
    }
    
    .mr-8
    {
        margin-right: 8% !important;
    }
    
    .mr-9
    {
        margin-right: 9% !important;
    }
    
    .mr-10
    {
        margin-right: 10% !important;
    }
    
    /* Margin Left */
    .ml-0
    {
        margin-left: 0 !important;
    }
    
    .ml-1
    {
        margin-left: 1% !important;
    }
    
    .ml-2
    {
        margin-left: 2% !important;
    }
    
    .ml-3
    {
        margin-left: 3% !important;
    }
    
    .ml-4
    {
        margin-left: 4% !important;
    }
    
    .ml-5
    {
        margin-left: 5% !important;
    }
    
    .ml-6
    {
        margin-left: 6% !important;
    }
    
    .ml-7
    {
        margin-left: 7% !important;
    }
    
    .ml-8
    {
        margin-left: 8% !important;
    }
    
    .ml-9
    {
        margin-left: 9% !important;
    }
    
    .ml-10
    {
        margin-left: 10% !important;
    }
    
    /* Margin Bottom */
    .mb-0
    {
        margin-bottom: 0 !important;
    }
    
    .mb-1
    {
        margin-bottom: 1% !important;
    }
    
    .mb-2
    {
        margin-bottom: 2% !important;
    }
    
    .mb-3
    {
        margin-bottom: 3% !important;
    }
    
    .mb-4
    {
        margin-bottom: 4% !important;
    }
    
    .mb-5
    {
        margin-bottom: 5% !important;
    }
    
    .mb-6
    {
        margin-bottom: 6% !important;
    }
    
    .mb-7
    {
        margin-bottom: 7% !important;
    }
    
    .mb-8
    {
        margin-bottom: 8% !important;
    }
    
    .mb-9
    {
        margin-bottom: 9% !important;
    }
    
    .mb-10
    {
        margin-bottom: 10% !important;
    }
    
    /* Padding All */
    .padding-1
    {
        padding: 1% !important;
    }
    
    .padding-2
    {
        padding: 2% !important;
    }
    
    .padding-3
    {
        padding: 3% !important;
    }
    
    .padding-4
    {
        padding: 4% !important;
    }
    
    .padding-5
    {
        padding: 5% !important;
    }
    
    .padding-6
    {
        padding: 6% !important;
    }
    
    .padding-7
    {
        padding: 7% !important;
    }
    
    .padding-8
    {
        padding: 8% !important;
    }
    
    .padding-9
    {
        padding: 9% !important;
    }
    
    .padding-10
    {
        padding: 10% !important;
    }
    
    .p-0
    {
        padding: 0 !important;
    }
    
    /* Padding Top */
    .pt-0
    {
        padding-top: 0 !important;
    }
    
    .pt-1
    {
        padding-top: 1% !important;
    }
    
    .pt-2
    {
        padding-top: 2% !important;
    }
    
    .pt-3
    {
        padding-top: 3% !important;
    }
    
    .pt-4
    {
        padding-top: 4% !important;
    }
    
    .pt-5
    {
        padding-top: 5% !important;
    }
    
    .pt-6
    {
        padding-top: 6% !important;
    }
    
    .pt-7
    {
        padding-top: 7% !important;
    }
    
    .pt-8
    {
        padding-top: 8% !important;
    }
    
    .pt-9
    {
        padding-top: 9% !important;
    }
    
    .pt-10
    {
        padding-top: 10% !important;
    }
    
    /* Padding Right */
    .pr-0
    {
        padding-right: 0 !important;
    }
    
    .pr-1
    {
        padding-right: 1% !important;
    }
    
    .pr-2
    {
        padding-right: 2% !important;
    }
    
    .pr-3
    {
        padding-right: 3% !important;
    }
    
    .pr-4
    {
        padding-right: 4% !important;
    }
    
    .pr-5
    {
        padding-right: 5% !important;
    }
    
    .pr-6
    {
        padding-right: 6% !important;
    }
    
    .pr-7
    {
        padding-right: 7% !important;
    }
    
    .pr-8
    {
        padding-right: 8% !important;
    }
    
    .pr-9
    {
        padding-right: 9% !important;
    }
    
    .pr-10
    {
        padding-right: 10% !important;
    }
    
    /* Padding Right */
    .pl-0
    {
        padding-left: 0 !important;
    }
    
    .pl-1
    {
        padding-left: 1% !important;
    }
    
    .pl-2
    {
        padding-left: 2% !important;
    }
    
    .pl-3
    {
        padding-left: 3% !important;
    }
    
    .pl-4
    {
        padding-left: 4% !important;
    }
    
    .pl-5
    {
        padding-left: 5% !important;
    }
    
    .pl-6
    {
        padding-left: 6% !important;
    }
    
    .pl-7
    {
        padding-left: 7% !important;
    }
    
    .pl-8
    {
        padding-left: 8% !important;
    }
    
    .pl-9
    {
        padding-left: 9% !important;
    }
    
    .pl-10
    {
        padding-left: 10% !important;
    }
    
    /* Padding Bottom */
    .pb-0
    {
        padding-bottom: 0 !important;
    }
    
    .pb-1
    {
        padding-bottom: 1% !important;
    }
    
    .pb-2
    {
        padding-bottom: 2% !important;
    }
    
    .pb-3
    {
        padding-bottom: 3% !important;
    }
    
    .pb-4
    {
        padding-bottom: 4% !important;
    }
    
    .pb-5
    {
        padding-bottom: 5% !important;
    }
    
    .pb-6
    {
        padding-bottom: 6% !important;
    }
    
    .pb-7
    {
        padding-bottom: 7% !important;
    }
    
    .pb-8
    {
        padding-bottom: 8% !important;
    }
    
    .pb-9
    {
        padding-bottom: 9% !important;
    }
    
    .pb-10
    {
        padding-bottom: 10% !important;
    }
    
    /* Minimum Height */
    .min-height-100
    {
        min-height: 100px !important;
    }
    
    .min-height-150
    {
        min-height: 150px !important;
    }
    
    .min-height-200
    {
        min-height: 200px !important;
    }
    
    .min-height-250
    {
        min-height: 250px !important;
    }
    
    .min-height-300
    {
        min-height: 300px !important;
    }
    
    @media (min-width: 576px)
    {
        .left-align-sm
        {
            text-align: left !important;
        }
        .right-align-sm
        {
            text-align: right !important;
        }
        .center-align-sm
        {
            text-align: center !important;
        }
    }
    
    @media (min-width: 768px)
    {
        .left-align-md
        {
            text-align: left !important;
        }
        .right-align-md
        {
            text-align: right !important;
        }
        .center-align-md
        {
            text-align: center !important;
        }
    }
    
    @media (min-width: 992px)
    {
        .left-align-lg
        {
            text-align: left !important;
        }
        .right-align-lg
        {
            text-align: right !important;
        }
        .center-align-lg
        {
            text-align: center !important;
        }
    }
    
    @media (min-width: 1200px)
    {
        .left-align-xl
        {
            text-align: left !important;
        }
        .right-align-xl
        {
            text-align: right !important;
        }
        .center-align-xl
        {
            text-align: center !important;
        }
    }
    
    .text-lowercase
    {
        text-transform: lowercase !important;
    }
    
    .text-uppercase
    {
        text-transform: uppercase !important;
    }
    
    .text-capitalize
    {
        text-transform: capitalize !important;
    }
    
    /* Icon Background Round */
    .background-round
    {
        padding: 15px;
    
        border-radius: 50%;
        background-color: rgba(0, 0, 0, .18);
    }
    
    /* opacity 0 */
    .opacity-0
    {
        opacity: 0;
    }
    
    /* Border None & Shadow None */
    .border-none
    {
        border-top: none !important;
        border-right: none !important;
        border-bottom: none !important;
        border-left: none !important;
    }
    
    .box-shadow-none
    {
        -webkit-box-shadow: none !important;
        box-shadow: none !important;
    }
    
    /* Margin 0 & Padding 0 */
    .no-margin
    {
        margin: 0 !important;
    }
    
    .no-padding
    {
        padding: 0 !important;
    }
    
    /* Position */
    .position-absolute
    {
        position: absolute;
    }
    
    .position-none
    {
        position: unset;
    }
    
    /* Vertical Align */
    .vertical-align-center
    {
        position: absolute;
        top: 50%;
    
        -webkit-transform: translateY(-50%);
        -moz-transform: translateY(-50%);
        -ms-transform: translateY(-50%);
        -o-transform: translateY(-50%);
        transform: translateY(-50%);
    }
    
    .vertical-align-bottom
    {
        vertical-align: bottom;
    }
    
    .vertical-align-super
    {
        vertical-align: super;
    }
    
    .vertical-text-top
    {
        vertical-align: text-top !important;
    }
    
    .vertical-text-sub
    {
        vertical-align: sub;
    }
    
    .vertical-text-middle
    {
        vertical-align: middle;
    }
    
    .height-100vh
    {
        height: 100vh;
    }
    
    /* Line Height */
    .line-height-0
    {
        line-height: 0 !important;
    }
    
    /* Icon Background */
    .icon-bg-circle
    {
        padding: .4rem;
    
        color: #fff;
        border-radius: 50%;
    }
    
    .text-shadow
    {
        text-shadow: -1px 2px 4px black;
    }
    
    .display-none
    {
        display: none;
    }
    
    .display-inline
    {
        display: inline;
    }
    
    .display-block
    {
        display: block;
    }
    
    .display-grid
    {
        display: grid;
    }
    
    .display-flex
    {
        display: -webkit-box;
        display: -webkit-flex;
        display:    -moz-box;
        display: -ms-flexbox;
        display:         flex;
    }
    
    .float-none
    {
        float: none !important;
    }
    
    .float-left
    {
        float: left !important;
    }
    
    .float-right
    {
        float: right !important;
    }
    
    .float-inherit
    {
        float: inherit !important;
    }
    
    .clear-both
    {
        clear: both;
    }
    
    ul.list-type-bullet
    {
        padding-left: 40px;
    
        list-style-type: inherit;
    }
    ul.list-type-bullet li
    {
        list-style-type: inherit;
    }
    
    .justify-content-end
    {
        -webkit-box-pack: end;
        -webkit-justify-content: flex-end;
        -moz-box-pack: end;
        -ms-flex-pack: end;
        justify-content: flex-end;
    }
    
    .text-ellipsis
    {
        overflow: hidden;
    
        white-space: nowrap;
        text-overflow: ellipsis;
    }
    
    /*---------------------------------
        Typography
    -----------------------------------*/
    a
    {
        text-decoration: none;
    }
    
    html
    {
        font-family: ${props => props.theme.font}, ${props =>
  props.theme.fontFallback} !important;
        font-weight: normal;
        line-height: 1.5;
    
        color: #6b6f82;
    }
    @media only screen and (min-width: 0)
    {
        html
        {
            font-size: 14px;
        }
    }
    @media only screen and (min-width: 992px)
    {
        html
        {
            font-size: 14.5px;
        }
    }
    @media only screen and (min-width: 1200px)
    {
        html
        {
            font-size: 15px;
        }
    }
    
    h1,
    h2,
    h3,
    h4,
    h5,
    h6
    {
        font-family: ${props => props.theme.font}, ${props =>
  props.theme.fontFallback};
        font-weight: 400;
        line-height: 1.1;
    
        color: #333;
    }
    
    p
    {
        font-family: ${props => props.theme.font}, ${props =>
  props.theme.fontFallback};
    }
    
    h1 a,
    h2 a,
    h3 a,
    h4 a,
    h5 a,
    h6 a
    {
        font-weight: inherit;
    }
    
    h1
    {
        font-size: 4.2rem;
        line-height: 110%;
    
        margin: 2.1rem 0 1.68rem 0;
    }
    
    h2
    {
        font-size: 3.56rem;
        line-height: 110%;
    
        margin: 1.78rem 0 1.424rem 0;
    }
    
    h3
    {
        font-size: 2.92rem;
        line-height: 110%;
    
        margin: 1.46rem 0 1.168rem 0;
    }
    
    h4
    {
        font-size: 2.28rem;
        line-height: 110%;
    
        margin: 1.14rem 0 .912rem 0;
    }
    
    h5
    {
        font-size: 1.64rem;
        line-height: 110%;
    
        margin: .82rem 0 .656rem 0;
    }
    
    h6
    {
        font-size: 1.15rem;
        line-height: 110%;
    
        margin: .575rem 0 .46rem 0;
    }
    
    em
    {
        font-style: italic;
    }
    
    strong
    {
        font-weight: 500;
    }
    
    small
    {
        font-size: 75%;
    }
    
    .light
    {
        font-weight: 300;
    }
    
    .thin
    {
        font-weight: 200;
    }
    
    .flow-text
    {
        font-weight: 300;
    }
    @media only screen and (min-width: 360px)
    {
        .flow-text
        {
            font-size: 1.2rem;
        }
    }
    @media only screen and (min-width: 390px)
    {
        .flow-text
        {
            font-size: 1.224rem;
        }
    }
    @media only screen and (min-width: 420px)
    {
        .flow-text
        {
            font-size: 1.248rem;
        }
    }
    @media only screen and (min-width: 450px)
    {
        .flow-text
        {
            font-size: 1.272rem;
        }
    }
    @media only screen and (min-width: 480px)
    {
        .flow-text
        {
            font-size: 1.296rem;
        }
    }
    @media only screen and (min-width: 510px)
    {
        .flow-text
        {
            font-size: 1.32rem;
        }
    }
    @media only screen and (min-width: 540px)
    {
        .flow-text
        {
            font-size: 1.344rem;
        }
    }
    @media only screen and (min-width: 570px)
    {
        .flow-text
        {
            font-size: 1.368rem;
        }
    }
    @media only screen and (min-width: 600px)
    {
        .flow-text
        {
            font-size: 1.392rem;
        }
    }
    @media only screen and (min-width: 630px)
    {
        .flow-text
        {
            font-size: 1.416rem;
        }
    }
    @media only screen and (min-width: 660px)
    {
        .flow-text
        {
            font-size: 1.44rem;
        }
    }
    @media only screen and (min-width: 690px)
    {
        .flow-text
        {
            font-size: 1.464rem;
        }
    }
    @media only screen and (min-width: 720px)
    {
        .flow-text
        {
            font-size: 1.488rem;
        }
    }
    @media only screen and (min-width: 750px)
    {
        .flow-text
        {
            font-size: 1.512rem;
        }
    }
    @media only screen and (min-width: 780px)
    {
        .flow-text
        {
            font-size: 1.536rem;
        }
    }
    @media only screen and (min-width: 810px)
    {
        .flow-text
        {
            font-size: 1.56rem;
        }
    }
    @media only screen and (min-width: 840px)
    {
        .flow-text
        {
            font-size: 1.584rem;
        }
    }
    @media only screen and (min-width: 870px)
    {
        .flow-text
        {
            font-size: 1.608rem;
        }
    }
    @media only screen and (min-width: 900px)
    {
        .flow-text
        {
            font-size: 1.632rem;
        }
    }
    @media only screen and (min-width: 930px)
    {
        .flow-text
        {
            font-size: 1.656rem;
        }
    }
    @media only screen and (min-width: 960px)
    {
        .flow-text
        {
            font-size: 1.68rem;
        }
    }
    @media only screen and (max-width: 360px)
    {
        .flow-text
        {
            font-size: 1.2rem;
        }
    }
    
    @media only screen and (max-width: 768px)
    {
        .nav-expanded .brand-sidebar
        {
            background: transparent !important;
        }
        .brand-sidebar .logo-wrapper
        {
            padding: 17px 18px !important;
    
            text-align: center;
    
            background: transparent;
        }
    }
    
    .small
    {
        font-size: 1.0rem !important;
    }
    
    .medium-small
    {
        font-size: .9rem !important;
    }
    
    .ultra-small
    {
        font-size: .8rem !important;
    }
    
    small
    {
        font-size: .8rem;
    }
    
    .strong
    {
        font-weight: 600;
    }
    
    h4.header
    {
        font-size: 1.4rem;
        font-weight: 400;
        line-height: 2.508rem;
    
        margin: 1.14rem 0 .912rem 0;
    
        text-transform: uppercase;
    }
    
    h4.header2
    {
        font-size: 1.1rem;
        font-weight: 400;
    
        text-transform: uppercase;
    }
    
    p.title
    {
        font-size: 1.3rem;
    }
    
    p.header
    {
        font-size: 1rem;
        font-weight: 500;
    
        text-transform: uppercase;
    }
    
    li.li-hover:hover
    {
        background: transparent !important;
    }
    
    li.search-out:hover
    {
        background: transparent;
    }
    
    li.mobile:before
    {
        background: #f7464a;
    }
    
    li.kitchen:before
    {
        background: #46bfbd;
    }
    
    li.home:before
    {
        background: #fdb45c;
    }
    
    .more-text
    {
        font-weight: 500;
    
        padding: 5px 20px;
    
        letter-spacing: 1px;
        text-transform: uppercase;
    }
    
    .valign-demo
    {
        height: 400px;
    
        background-color: #ddd;
    }
    
    .margin
    {
        margin: 0 !important;
    }
    
    .uppercase
    {
        text-transform: uppercase;
    }
    
    /*----------------------------------------
      Grid
    ------------------------------------------*/
    .section
    {
        padding: .5rem 0;
    }
    
    .row
    {
        margin-bottom: 0;
    }
    .row .col
    {
        padding: 0 1rem;
    }
    
    
    /*----------------------------------------
    \tAvatar
    ------------------------------------------*/
    .avatar-status
    {
        line-height: 50px;
    
        position: relative;
    
        display: inline-block;
    
        width: 28px;
    
        vertical-align: bottom;
        white-space: nowrap;
    
        border-radius: 50px;
    }
    .avatar-status i
    {
        position: absolute;
        right: -2px;
        bottom: 18px;
    
        width: 9px !important;
        height: 9px !important;
    
        border: 1px solid #fff;
        border-radius: 100%;
    }
    .avatar-status span.text-circle
    {
        font-size: 1.2rem;
    
        display: table-cell;
    
        text-align: center;
        vertical-align: middle;
    
        color: #fff;
        background: #fafafa;
    }
    .avatar-status img
    {
        width: 100%;
        max-width: 100%;
        height: auto;
    
        border: 0 none;
        border-radius: 1000px;
        background: #e6e6e6;
    }
    
    .avatar-online i
    {
        background-color: #00e676;
    }
    
    .avatar-off i
    {
        background-color: #bdbdbd;
    }
    
    .avatar-busy i
    {
        background-color: #ff1744;
    }
    
    .avatar-away i
    {
        background-color: #ffc400;
    }
    
    
    /*----------------------------------------
    \tDropdown
    ------------------------------------------*/
    .dropdown-content li:hover,
    .dropdown-content li.active
    {
        background-color: #eee;
    }
    
    .dropdown-content li > a,
    .dropdown-content li > span
    {
        padding: 14px 24px;
    }
    .dropdown-content li > a:hover,
    .dropdown-content li > a.active,
    .dropdown-content li > span:hover,
    .dropdown-content li > span.active
    {
        background-color: #eee;
    }
    
    .dropdown-content li > a > i
    {
        width: 24px;
        margin: 0 12px 0 0;
    }
    
    /*----------------------------------------
    \tBadges
    ------------------------------------------*/
    span.badge
    {
        color: #fff;
    }
    span.badge.pill
    {
        font-size: .8rem;
        line-height: 20px;
    
        min-width: 1rem;
        height: 20px;
    
        border-radius: 50%;
        border-radius: 9px;
    }
    
    #badges-navbar nav .brand-logo
    {
        font-size: 2.1rem;
    }
    
    /*----------------------------------------
      Material
    ------------------------------------------*/
    
    .material-icons
    {
        font-size: 24px;
        font-weight: normal;
        font-style: normal;
        line-height: 1;
        /* Preferred icon size */
    
        display: inline-block;
    
        white-space: nowrap;
        letter-spacing: normal;
        text-transform: none;
        word-wrap: normal;
    
        direction: ltr;
        /* Support for all WebKit browsers. */
        -webkit-font-smoothing: antialiased;
        /* Support for Safari and Chrome. */
        text-rendering: optimizeLegibility;
        /* Support for Firefox. */
        -moz-osx-font-smoothing: grayscale;
        /* Support for IE. */
        -webkit-font-feature-settings: 'liga';
        -moz-font-feature-settings: 'liga';
        font-feature-settings: 'liga';
    }
    
    /*----------------------------------------
    Cards
    ------------------------------------------*/
    .card
    {
        overflow: hidden;
    
        margin: 1rem 0 1rem 0;
    }
    .card .card-title
    {
        font-size: 18px;
        font-weight: 400;
    
        margin: 0;
    }
    
    
    /*
    * Custom Animations
    */
    @-webkit-keyframes fadeUp
    {
        0%
        {
            -webkit-transform: translateY(30px);
            transform: translateY(30px);
    
            opacity: 0;
        }
        100%
        {
            -webkit-transform: translateY(0px);
            transform: translateY(0px);
    
            opacity: 1;
        }
    }
    @-moz-keyframes fadeUp
    {
        0%
        {
            -moz-transform: translateY(30px);
            transform: translateY(30px);
    
            opacity: 0;
        }
        100%
        {
            -moz-transform: translateY(0px);
            transform: translateY(0px);
    
            opacity: 1;
        }
    }
    @-o-keyframes fadeUp
    {
        0%
        {
            -o-transform: translateY(30px);
            transform: translateY(30px);
    
            opacity: 0;
        }
        100%
        {
            -o-transform: translateY(0px);
            transform: translateY(0px);
    
            opacity: 1;
        }
    }
    @keyframes fadeUp
    {
        0%
        {
            -webkit-transform: translateY(30px);
            -moz-transform: translateY(30px);
            -o-transform: translateY(30px);
            transform: translateY(30px);
    
            opacity: 0;
        }
        100%
        {
            -webkit-transform: translateY(0px);
            -moz-transform: translateY(0px);
            -o-transform: translateY(0px);
            transform: translateY(0px);
    
            opacity: 1;
        }
    }
    
    .animate.fadeUp
    {
        -webkit-animation: fadeUp;
        -moz-animation: fadeUp;
        -o-animation: fadeUp;
        animation: fadeUp;
        -webkit-animation-duration: 1.5s;
        -moz-animation-duration: 1.5s;
        -o-animation-duration: 1.5s;
        animation-duration: 1.5s;
    
        -webkit-animation-fill-mode: both;
        -moz-animation-fill-mode: both;
        -o-animation-fill-mode: both;
        animation-fill-mode: both;
    }
    
    @-webkit-keyframes fadeLeft
    {
        0%
        {
            -webkit-transform: translateX(-30px);
            transform: translateX(-30px);
    
            opacity: 0;
        }
        100%
        {
            -webkit-transform: translateX(0px);
            transform: translateX(0px);
    
            opacity: 1;
        }
    }
    
    @-moz-keyframes fadeLeft
    {
        0%
        {
            -moz-transform: translateX(-30px);
            transform: translateX(-30px);
    
            opacity: 0;
        }
        100%
        {
            -moz-transform: translateX(0px);
            transform: translateX(0px);
    
            opacity: 1;
        }
    }
    
    @-o-keyframes fadeLeft
    {
        0%
        {
            -o-transform: translateX(-30px);
            transform: translateX(-30px);
    
            opacity: 0;
        }
        100%
        {
            -o-transform: translateX(0px);
            transform: translateX(0px);
    
            opacity: 1;
        }
    }
    
    @keyframes fadeLeft
    {
        0%
        {
            -webkit-transform: translateX(-30px);
            -moz-transform: translateX(-30px);
            -o-transform: translateX(-30px);
            transform: translateX(-30px);
    
            opacity: 0;
        }
        100%
        {
            -webkit-transform: translateX(0px);
            -moz-transform: translateX(0px);
            -o-transform: translateX(0px);
            transform: translateX(0px);
    
            opacity: 1;
        }
    }
    
    .animate.fadeLeft
    {
        -webkit-animation: fadeLeft;
        -moz-animation: fadeLeft;
        -o-animation: fadeLeft;
        animation: fadeLeft;
        -webkit-animation-duration: 1.5s;
        -moz-animation-duration: 1.5s;
        -o-animation-duration: 1.5s;
        animation-duration: 1.5s;
    
        -webkit-animation-fill-mode: both;
        -moz-animation-fill-mode: both;
        -o-animation-fill-mode: both;
        animation-fill-mode: both;
    }
    
    @-webkit-keyframes fadeRight
    {
        0%
        {
            -webkit-transform: translateX(30px);
            transform: translateX(30px);
    
            opacity: 0;
        }
        100%
        {
            -webkit-transform: translateX(0px);
            transform: translateX(0px);
    
            opacity: 1;
        }
    }
    
    @-moz-keyframes fadeRight
    {
        0%
        {
            -moz-transform: translateX(30px);
            transform: translateX(30px);
    
            opacity: 0;
        }
        100%
        {
            -moz-transform: translateX(0px);
            transform: translateX(0px);
    
            opacity: 1;
        }
    }
    
    @-o-keyframes fadeRight
    {
        0%
        {
            -o-transform: translateX(30px);
            transform: translateX(30px);
    
            opacity: 0;
        }
        100%
        {
            -o-transform: translateX(0px);
            transform: translateX(0px);
    
            opacity: 1;
        }
    }
    
    @keyframes fadeRight
    {
        0%
        {
            -webkit-transform: translateX(30px);
            -moz-transform: translateX(30px);
            -o-transform: translateX(30px);
            transform: translateX(30px);
    
            opacity: 0;
        }
        100%
        {
            -webkit-transform: translateX(0px);
            -moz-transform: translateX(0px);
            -o-transform: translateX(0px);
            transform: translateX(0px);
    
            opacity: 1;
        }
    }
    
    .animate.fadeRight
    {
        -webkit-animation: fadeRight;
        -moz-animation: fadeRight;
        -o-animation: fadeRight;
        animation: fadeRight;
        -webkit-animation-duration: 1.5s;
        -moz-animation-duration: 1.5s;
        -o-animation-duration: 1.5s;
        animation-duration: 1.5s;
    
        -webkit-animation-fill-mode: both;
        -moz-animation-fill-mode: both;
        -o-animation-fill-mode: both;
        animation-fill-mode: both;
    }
    
    .animation-fast
    {
        -webkit-animation-delay: .1s;
        -moz-animation-delay: .1s;
        -o-animation-delay: .1s;
        animation-delay: .1s;
    }
    
    .animation-slow
    {
        -webkit-animation-delay: 2s;
        -moz-animation-delay: 2s;
        -o-animation-delay: 2s;
        animation-delay: 2s;
    }
    
    .delay-1
    {
        -webkit-animation-delay: .3s !important;
        -moz-animation-delay: .3s !important;
        -o-animation-delay: .3s !important;
        animation-delay: .3s !important;
    }
    
    .delay-2
    {
        -webkit-animation-delay: .4s !important;
        -moz-animation-delay: .4s !important;
        -o-animation-delay: .4s !important;
        animation-delay: .4s !important;
    }
    
    .delay-3
    {
        -webkit-animation-delay: .5s !important;
        -moz-animation-delay: .5s !important;
        -o-animation-delay: .5s !important;
        animation-delay: .5s !important;
    }
    
    .delay-4
    {
        -webkit-animation-delay: .6s !important;
        -moz-animation-delay: .6s !important;
        -o-animation-delay: .6s !important;
        animation-delay: .6s !important;
    }
    
    .delay-5
    {
        -webkit-animation-delay: .7s !important;
        -moz-animation-delay: .7s !important;
        -o-animation-delay: .7s !important;
        animation-delay: .7s !important;
    }
    
    .collapsible-header.cyan {
        color: #fff;
    }
    .panel--box{
        min-height: 500px;
        padding: 30px;
    }
    .menu--list li{
        background: #eee;
        padding: 10px;
        margin-bottom: 4px;
    }
    .menu--list span{
        color:#333;
    }
    .right--button a{
        margin: 0px 10px;
    }
    .dropdown-content li > a, .dropdown-content li > span {
        color: #957bb3 !important;
    }
    .select-wrapper input.select-dropdown:focus {
        border-bottom: 1px solid #8d62c1 !important;
        box-shadow: 0 1px 0 0 #8d62c1 !important;
    }
    .tab--content{
        padding:30px 30px 60px;
    }
    .media-image {
        margin-bottom: 10px;
        height: 115px;
        width: 115px;
        overflow: hidden;
        line-height: 115px;
    }
    .media-image.selected {
        border: 1px solid #6b4994;
    }
    .media-image img {
        width: 100%;
        vertical-align: middle;
        display: inline-block;
    }
    .media-image.selected img {
        opacity: 0.8;
    }
    .permission--box span{
        margin-right: 15px
    }
    .collapsible-header{
        color: #fff;
    }

`;
